// <auto-generated />
namespace RuSpeak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addUser_toComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUser_toComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201410011218333_addUser_toComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
